services:

    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    #
    # Index Provider for Dynamic Search Bundle
    #
    DsLuceneBundle\Provider\LuceneIndexProvider:
        tags:
            - { name: 'dynamic_search.index_provider', identifier: 'lucene' }